services:
  postgres-db:
    image: postgres:16.3-alpine3.18
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - '5432:5432'
    volumes:
      - './postgres-data:/var/lib/postgresql/data'
